# Generated by Django 2.1.7 on 2019-03-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20190323_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=16),
        ),
    ]
