# Generated by Django 2.1.7 on 2019-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_auto_20190324_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='location',
            new_name='github_location',
        ),
        migrations.RenameField(
            model_name='newproject',
            old_name='imglocation',
            new_name='image_location',
        ),
        migrations.RenameField(
            model_name='newproject',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='newproject',
            old_name='title',
            new_name='project_title',
        ),
    ]
